services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
  backend:
    build: ./server
    container_name: ptm-backend
    ports:
      - "3101:3000"
    volumes:
      - backend-data:/app/data
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: ptm-frontend
    ports:
      - "8101:80"
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  grafana-storage: {}
  prometheus-data: {}
  backend-data: {}
