mappings:
  - match: "scale.*.*.*"
    name: "${3}"
    labels:
      instance: "${1}"
      job: "TrueNAS Scale Graphite Exporter"
      type: "${2}"
  - match: "scale.*.*.*.*"
    name: "${3}_${4}"
    labels:
      instance: "${1}"
      job: "TrueNAS Scale Graphite Exporter"
      type: "${2}"
