mappings:
  - match: "servers.*.*.*"
    name: "${3}"
    labels:
      instance: "${1}"
      job: "TRUENAS-SAN-HDD-01"
      type: "${2}"
  - match: "servers.*.*.*.*"
    name: "${3}_${4}"
    labels:
      instance: "${1}"
      job: "TRUENAS-SAN-HDD-01"
      type: "${2}"
