global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "prometheus_target_manager"
    http_sd_configs:
      - url: "http://172.24.0.14:80/api/targets"
