global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "target_manager"
    http_sd_configs:
      - url: "http://backend:3101/api/targets"
