global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "prometheus_target_manager"
    http_sd_configs:
      - url: "http://172.24.0.14:80/api/targets"

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files:
          - "/opt/prometheus/targets/services.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.24.0.15:9115 # Blackbox exporter address
