global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "target_manager"
    http_sd_configs:
      - url: "http://docker.brokeserver.live:3101/api/targets"
